# Generated by Django 5.0.4 on 2024-05-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_to_cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
