# Generated by Django 5.0.4 on 2024-05-30 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_customer'),
        ('website', '0002_add_to_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_to_cart',
            name='cart_status',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_date', models.DateTimeField(auto_now=True)),
                ('cart_item', models.ManyToManyField(related_name='cart_list', to='website.add_to_cart')),
                ('customer_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.customer')),
            ],
        ),
    ]
