# Generated by Django 5.0.4 on 2024-06-03 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_customer'),
        ('website', '0003_add_to_cart_cart_status_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_to_cart',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='adminpanel.product'),
        ),
    ]
