# Generated by Django 5.0.4 on 2024-05-09 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_old_price', models.FloatField()),
                ('product_new_price', models.FloatField()),
                ('product_description', models.TextField()),
                ('cat', models.ForeignKey(blank=True, null=20, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.category')),
            ],
        ),
        migrations.CreateModel(
            name='product_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_image/')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod', to='adminpanel.product')),
            ],
        ),
    ]
