# Generated by Django 5.0.4 on 2024-05-13 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.ForeignKey(blank=True, null=20, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='adminpanel.category'),
        ),
    ]
